USE monitoring;
ALTER TABLE NOTIFICATION ADD testSubType VARCHAR(64) NOT NULL;
ALTER TABLE NOTIFICATION ADD scope VARCHAR(128) NOT NULL;
UPDATE NOTIFICATION SET scope='/d4science.research-infrastructures.eu';
UPDATE NOTIFICATION SET testSubType='MEMORY_AVAILABLE'  WHERE testType='MEMORY_AVAILABLE';
UPDATE NOTIFICATION SET testSubType='CPU_LOAD'  WHERE testType='CPU_LOAD';
UPDATE NOTIFICATION SET testSubType='DISK_QUOTA'  WHERE testType='DISK_QUOTA';
UPDATE NOTIFICATION SET testSubType='GHN_READY' WHERE MESSAGE LIKE '%GHN Ready%';
UPDATE NOTIFICATION SET testSubType='GHN_SHUTDOWN' WHERE MESSAGE LIKE '%GHN shutdown%';
UPDATE NOTIFICATION SET testSubType='SCOPE_ADDED' WHERE MESSAGE LIKE '%Added%';
UPDATE NOTIFICATION SET testSubType='SCOPE_REMOVED' WHERE MESSAGE LIKE '%Removed%';

USE accounting;
ALTER TABLE NODEACCOUNTING ADD INDEX GHNIndex(GHNName);
ALTER TABLE NODEACCOUNTING ADD INDEX ServicesIndex(ServiceClass,ServiceName);
ALTER TABLE NODEACCOUNTING ADD INDEX CallerScopeIndex(callerScope);

